AWSTemplateFormatVersion: '2010-09-09'
Description: API Gateway v2 HTTP API directly integrated with SQS

Parameters:
  ApiName:
    Type: String
    Default: HttpApiToSqs

Resources:
  SQSQueue:
    Type: AWS::SQS::Queue

  ApiGatewayRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: apigateway.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: SqsSendMessage
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action: sqs:SendMessage
                Resource: !GetAtt SQSQueue.Arn

  HttpApi:
    Type: AWS::ApiGatewayV2::Api
    Properties:
      Name: !Ref ApiName
      ProtocolType: HTTP

  Integration:
    Type: AWS::ApiGatewayV2::Integration
    Properties:
      ApiId: !Ref HttpApi
      IntegrationType: AWS_PROXY
      IntegrationSubtype: SQS-SendMessage
      CredentialsArn: !GetAtt ApiGatewayRole.Arn
      PayloadFormatVersion: 1.0
      RequestParameters:
        QueueUrl: !Ref SQSQueue
        MessageBody: "$request.body"

  Route:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref HttpApi
      RouteKey: "POST /{proxy+}"
      Target: !Join [ "/", [ "integrations", !Ref Integration ] ]

  Stage:
    Type: AWS::ApiGatewayV2::Stage
    Properties:
      ApiId: !Ref HttpApi
      StageName: prod
      AutoDeploy: true

Outputs:
  ApiEndpoint:
    Value: !Sub "https://${HttpApi}.execute-api.${AWS::Region}.amazonaws.com/prod"
  QueueUrl:
    Value: !Ref SQSQueue

